workers: 6
display: 100
epoches: 20
batch_size: 128
base_lr: 0.0002
beta1: 0.5

dataset: 'celebA'
image_size: 64
z_size: 100
channel_size: 3
ngf: 128
ndf: 128
#-------------lr_policy--------------------#
# step
#lr_policy: 'step'
#policy_parameter:
  #gamma: 0.333
  #step_size: 35000
# exp
# lr_policy: 'exp'
# policy_parameter:
#   gamma: 0.99
# 
# inv
# lr_policy: 'inv'
# policy_parameter:
#   gamma: 0.1
#   power: 0.1
# 
# multistep
#lr_policy: 'multistep'
#policy_parameter:
  #stepvalue: [20000, 35000, 45000]
  #gamma: 0.1
# 
# poly
#lr_policy: 'poly'
#policy_parameter:
  #power: 1.5
  #max_iter: 250000
# 
# sigmoid
# lr_policy: 'sigmoid'
# policy_parameter:
#   gamma: 0.9
#   stepsize: 5000
#lr_policy: 'multistep-poly'
#policy_parameter:
  #stepvalue: [17500, 35000, 52500, 70000]
  #max_iter: 87500
  #gamma: 0.333
  #power: 1.1
